<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Shopbybrand
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php /** @var \Mavenbird\Shopbybrand\Block\Brand\View $block */
$brandName = $block->getBrand()->getValue(); ?>
<script>
    require(['jquery'], function ($) {
        $(".navigation li.mbbrand-top-link").addClass("active");
    });
</script>
<div class="brand-information"> 
    <div class="brand-detail">
        <?php if ($image = $block->getBrandImage()): ?>
            <div class="brand-image-container">
                <img class="brand-image-photo"
                     src="<?= /** @noEscape */ $block->getBrandImage() ?>"
                     alt="<?= $escaper->escapeHtml($brandName) ?>" title="<?= $escaper->escapeHtml($brandName) ?>">
            </div>
        <?php endif; ?>
        <?php if ($description = $block->getBrandDescription()): ?>
            <div class="brand-description-container">
                <div class="brand-description">
                    <?= /** @noEscape */ $description ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <?php if ($blockHtml = $block->getStaticContent()): ?>
    <div class="brand-cms-container">
        <div class="brand-static-block">
            <?= /** @noEscape */ $blockHtml ?>
        </div>
    </div>
    <?php endif; ?>
</div>

<style type="text/css">
    .brand-information .brand-detail .brand-image-photo {
        width: <?= /** @noEscape */ $block->getLogoWidth() . 'px' ?>;
        height: <?= /** @noEscape */ $block->getLogoHeight() . 'px' ?>
    }
</style>

