<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Shopbybrand
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */

/** @var \Mavenbird\Shopbybrand\Block\Design $block */
$helper = $block->helper();
?>
<style type="text/css">
    .block-brand-list .brand-list-content .product-item-info .product-image-photo {
        width: <?= /** @noEscape */ $block->getLogoWidth() . 'px' ?>;
        height: <?= /** @noEscape */ $block->getLogoHeight() . 'px' ?>
    }
    /*===================================================================
    |                            Configuration Style                    |
    ====================================================================*/
    <?php if ($color = $helper->getBrandConfig('color')): ?>
    .block-brand-search,
    .block-brand-list ul.brand-options li.active {
        background-color: <?= /** @noEscape */ $color ?>;
        border-color:  <?= /** @noEscape */ $color ?>;
    }
    .category-nav-list li.active {
        background-color: <?= /** @noEscape */ $color ?>;
    }

    <?php endif; ?>

    <?php if ($helper->enableSearch() || $helper->enableFeature()): ?>
    .page-title-wrapper {
        display: none
    }

    <?php endif; ?>
    /*===================================================================
    |                           Custom STYLE                             |
    ====================================================================*/
    <?= /** @noEscape */ $block->getCustomCss() ?>

    /*===================================================================
    |           Brand Page product List Responsive Design                |
    ====================================================================*/

    .brand-list-content li {
        width: <?= $helper->getBrandConfig('display') === \Mavenbird\Shopbybrand\Model\Config\Source\BrandListDisplay::DISPLAY_LABEL
        ? '33%' : '16.3% !important' ?>;
    }   
    .block-brand-list .quickview_popup a {
        background-color: <?= /** @noEscape */ $color ?>;
    }

</style>
