<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Shopbybrand
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */

/** @var Mavenbird\Shopbybrand\Block\Sidebar\BrandCategory $block */
$categories = $block->getCategories();
?>
<div class="block block-category-brand widget" id="block-category-brand-container">
    <div class="block-title">
        <strong role="heading" aria-level="2" class="block-subtitle"
                id="category-brand-subtitle"><?= /** @noEscape */ $block->getTitle() ?></strong>
    </div>
    <div class="block-content">
        <?php if ($categories->getSize()): ?>
            <div class="filter-options-content" id='category-brand-menu'>
                <ul>
                    <?php foreach ($categories as $category): ?>
                        <?php if ($block->getBrandQty($category->getId())): ?>
                            <li>
                                <a href="<?= $escaper->escapeUrl($block->getCatUrl($category)) ?>">
                                    <span><?= /** @noEscape */ $block->showBrandQty()
                                            ? $escaper->escapeHtml($category->getName() . ' (' . $block->getBrandQty($category->getId()) . ')')
                                            : $escaper->escapeHtml($category->getName()) ?></span>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php else: ?>
            <div class="filter-options-content" id='category-brand-menu'>
                <span><?= /** @noEscape */
                    __('No categories available.') ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
