<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Shopbybrand
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */

/** @var Mavenbird\Shopbybrand\Block\Link\CategoryMenu $block */
$brands = $block->getCollection();
$showDropdownMenu = $block->enableDropdownMenu() && $brands->getData() ;
$count  = 0;
$limit = $block->getLimit();
?>
<li class="ui-menu-item level0 fullwidth parent mmbrand-top-link" role="presentation">
    <a href="<?= $escaper->escapeUrl($block->getBrandUrl()) ?>"
       class="level-top ui-corner-all" id="ui-id-8" tabindex="-1" role="menuitem">
        <span><?= $escaper->escapeHtml($block->getBrandTitle()) ?></span>
    </a>
<?php if ($showDropdownMenu): ?>
    <div class="level0 submenu">
        <div class="container">
            <div class="row">
                <ul class="subchildmenu col-sm-12 mega-columns columns4">
                    <?php foreach ($brands as $brand): ?>
                        <li class="ui-menu-item level1">
                            <img class="img-responsive brand-topmenu-image"
                                 src="<?= /** @noEscape */ $brand->getImage()
                                     ? $escaper->escapeUrl($block->getBrandThumbnail($brand))
                                     : $escaper->escapeUrl($block->getBrandImageUrl($brand)) ?>"
                                 alt="<?= $escaper->escapeHtml($brand->getValue()) ?>"/>
                            <a href="<?= /** @noEscape */ $block->getBrandUrl($brand) ?>"
                               id="ui-brand-id-<?= /** @noEscape */ $brand->getId() ?>"
                               class="ui-corner-all Mavenbird-brands-topmenu" tabindex="-1" role="menuitem">
                                <span style="padding-left: 10px">
                                    <?= $escaper->escapeHtml($brand->getValue()) ?>
                                </span>
                            </a>
                        </li>
                        <?php $count++;
                        if ($count === $limit) {
                            break;
                        } ?>
                    <?php endforeach; ?>
                    <li class="ui-menu-item level1"
                        style="border-top:solid 1px #dfdfdf; margin: 0 5px; ">
                        <a href="<?= $escaper->escapeUrl($block->getBrandUrl()) ?>"
                           id="ui-all-brand" class="ui-corner-all"
                           tabindex="-1" role="menuitem">
                            <span style="padding-left: 10px;"><?= /** @noEscape */ __('View All') ?></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
</li>
