<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Shopbybrand
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */

/** @var Mavenbird\Shopbybrand\Block\Link\CategoryMenu $block */
$brands = $block->getCollection();
$showDropdownMenu = $block->enableDropdownMenu() && $brands->getData() ;
$count  = 0;
$limit = $block->getLimit();
?>
<li class="level0 nav-8 last level-top parent ui-menu-item mbbrand-top-link" role="presentation">
    <a href="<?= $escaper->escapeUrl($block->getBrandUrl()) ?>"
       class="level-top ui-corner-all" id="ui-id-8" tabindex="-1" role="menuitem">
        <?php if ($showDropdownMenu): ?>
            <span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span>
        <?php endif; ?>
        <span><?= $escaper->escapeHtml($block->getBrandTitle()) ?></span>
    </a>
    <?php if ($showDropdownMenu): ?>
        <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" role="menu"
                aria-expanded="false" style="display: none; top: 47px; left: -0.15625px;padding: 10px 0"
                aria-hidden="true">
                <div class="ui-menu-item" role="presentation">
                    <?php foreach ($brands as $brand): ?>
                        <li class="level1 nav-8-<?= /** @noEscape */ $count ?> ui-menu-item" role="presentation">
                            <img class="img-responsive brand-topmenu-image"
                                 src="<?= /** @noEscape */ $brand->getImage()
                                     ? $escaper->escapeUrl($block->getBrandThumbnail($brand))
                                     : $escaper->escapeUrl($block->getBrandImageUrl($brand)) ?>"
                                 alt="<?= $escaper->escapeHtml($brand->getValue()) ?>"/>
                            <a href="<?= /** @noEscape */ $block->getBrandUrl($brand) ?>"
                               id="ui-brand-id-<?= /** @noEscape */ $brand->getId() ?>"
                               class="ui-corner-all" tabindex="-1"
                               role="menuitem">
                                <span style="padding-left: 10px">
                                    <?= $escaper->escapeHtml($brand->getValue()) ?>
                                </span>
                            </a>
                        </li>
                        <?php
                        $count++;
                        if ($count === $limit) {
                            break;
                        }
                    endforeach; ?>
                </div>
                <li class="level1 nav-8-<?= /** @noEscape */ $count + 1 ?> ui-menu-item"
                    style="border-top:solid 1px #dfdfdf; margin: 0 5px; " role="presentation">
                    <a href="<?= $escaper->escapeUrl($block->getBrandUrl()) ?>"
                       id="ui-all-brand" class="ui-corner-all"
                       tabindex="-1" role="menuitem">
                        <span style="padding-left: 10px;"><?= /** @noEscape */ __('View All') ?></span>
                    </a>
                </li>
            </ul>
    <?php endif; ?>
</li>


