<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Shopbybrand
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */

/** @var Mavenbird\Shopbybrand\Block\Product\Logo $block */
?>
<?php if ($brand = $block->getBrandObject()): ?>
    <?php if ($block->showBrandInfo() === 'logo'): ?>
        <div class="product-brand-logo">
            <a href="<?= /** @noEscape */ $block->helper()->getBrandUrl($brand) ?>">
                <img src="<?= /** @noEscape */ $block->helper()->getBrandImageUrl($brand) ?>"
                     title="<?= /** @noEscape */ $brand->getValue() ?>"
                     alt="<?= /** @noEscape */ $brand->getValue() ?>"
                     style="width: <?= /** @noEscape */ $block->getLogoWidth() . 'px' ?>;
                            height: <?= /** @noEscape */ $block->getLogoHeight() . 'px' ?>;">
            </a>
        </div>
    <?php else: ?>
        <div class="product-brand-name">
            <a href="<?= /** @noEscape */ $block->helper()->getBrandUrl($brand) ?>">
                <span title="<?= $escaper->escapeHtml($brand->getValue()) ?>"><?= $escaper->escapeHtml($brand->getValue()) ?></span>
            </a>
        </div>
    <?php endif; ?>
<?php endif; ?>
