<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Shopbybrand
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */

/** @var \Mavenbird\Shopbybrand\Block\Sidebar\Featured $block */
$featureBrands = $block->getFeaturedBrand();
$timeId = time();
$isEnableNavigation = $block->getEnableNavigation();
$isEnableDots = $block->getEnableDots();

if (!empty($featureBrands)): ?>
    <?= /** @noEscape */ $block->includeCssLib() ?>
    <div class="block block-brand-feature widget">
        <?php if ($block->showTitle()): ?>
            <div class="block-title">
                <strong id="block-feature-brand-heading" role="heading"
                        aria-level="2"><?= /** @noEscape */ $block->getFeatureTitle() ?></strong>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <div class="owl-carousel owl-theme brand-carousel"
                 id="feature-brand-carousel-<?= /** @noEscape */ $timeId ?>"
                 data-mage-init='{"brandSlider": {}}'>
                <?php foreach ($featureBrands as $brand): ?>
                    <div class="relate-content item">
                        <a href="<?= /** @noEscape */ $block->helper()->getBrandUrl($brand) ?>">
                            <img class="img-responsive brand-image"
                                 src="<?= /** @noEscape */ $block->helper()->getBrandImageUrl($brand) ?>" alt="">
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script>
  window.isEnableConfig = <?= /** @noEscape */ $isEnableNavigation ?>;
  window.isEnableDots = <?= /** @noEscape */ $isEnableDots ?>;
</script>
