<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Shopbybrand
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */

/** @var \Mavenbird\Shopbybrand\Block\Sidebar\BrandList $block */
$brands = $block->getCollection();
if (!empty($brands)):?>
<div class="block block-brand-thumbnail widget" id="block-brand-thumbnail-container">
    <div class="block-title">
        <strong role="heading" aria-level="2" class="block-subtitle"
                id="thumbnail-brand-subtitle"><?= /** @noEscape */ $block->getTitle() ?></strong>
    </div>
    <div class="block-content">
        <div class="filter-options-content" id='brand-thumbnail-menu'>
            <ul>
                <?php foreach ($brands as $brand): ?>
                        <li>
                            <a href='<?= /** @noEscape */ $block->getBrandUrl($brand) ?>'>
                                <div class="brand-items"
                                     id="item-<?= /** @noEscape */ $brand->getId() ?>">
                                    <img class="img-responsive brand-thumbnail-image"
                                         src="<?= $brand->getImage() ? $escaper->escapeUrl($block->getBrandThumbnail($brand))
                                             : $escaper->escapeUrl($block->helper()->getBrandImageUrl($brand)) ?>"
                                         style="width: 40px;height: 40px; float: left;" alt=""/>
                                    <span><?= /** @noEscape */ $brand->getValue() ?></span>
                                </div>
                            </a>
                        </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="pages" id="brand-thumbnail-bottom" style="margin-top:10px">
            <a class="action" href="<?= /** @noEscape */ $block->getBrandUrl() ?>" style="width:auto;">
                <span><?= /** @noEscape */ __('View All') ?></span>
            </a>
        </div>
    </div>
</div>
<?php endif; ?>
