<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Shopbybrand
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */

$timeId = time();
/** @var \Mavenbird\Shopbybrand\Block\Brand\Featured $block */
$featureBrands = $block->getFeaturedBrand();
$style = $block->getStyleDisplayFeature();
$isEnableNavigation = $block->getEnableNavigation();
$isEnableDots = $block->getEnableDots();
?>
<?php if (!empty($featureBrands)): ?>
    <?= /** @noEscape */ $block->includeCssLib() ?>
    <div class="block-brand-feature widget">
        <div class="block-title" style="text-align: center;">
            <strong id="block-feature-brand-heading" role="heading"
                    aria-level="2"><?= /** @noEscape */ $block->getFeatureTitle() ?></strong>
        </div>
        <div class="block-content">
            <?php if (!empty($featureBrands) &&
            $style === \Mavenbird\Shopbybrand\Model\Config\Source\FeatureStyle::DISPLAY_SLIDER): ?>
            <div class="owl-carousel owl-theme brand-carousel"
                 id="feature-brand-carousel-<?= /** @noEscape */ $timeId ?>"
                 data-mage-init='{"brandSlider": {}}'>
            <?php endif; ?>
                <?php foreach ($featureBrands as $brand): ?>
                    <?php if ($style === \Mavenbird\Shopbybrand\Model\Config\Source\FeatureStyle::DISPLAY_SLIDER): ?>
                <div class="relate-content item">
                    <?php else: ?>
                    <div class="relate-content item mb-2 mb-sm-4 mb-xs-6 col-mb" style="float: left; padding: 5px 0;">
                    <?php endif; ?>
                        <a href="<?= /** @noEscape */ $block->helper()->getBrandUrl($brand) ?>">
                            <img class="img-responsive brand-image"
                                 src="<?= /** @noEscape */ $block->helper()->getBrandImageUrl($brand) ?>"
                                 width="<?= /** @noEscape */ $block->getLogoWidth() ?>"
                                 height="<?= /** @noEscape */ $block->getLogoHeight() ?>"
                                 alt="">
                            <?php if ($block->showLabel()): ?>
                                <span><?= /** @noEscape */ $brand->getValue() ?></span>
                            <?php endif; ?>
                        </a>
                    </div>
                <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<div style="clear: both"></div>
<script>
  window.isEnableConfig = <?= /** @noEscape */ $isEnableNavigation ?>;
  window.isEnableDots = <?= /** @noEscape */ $isEnableDots ?>;
</script>

